var imgDatabase = [
  {
    type: 'img',
    src: 'img/01.jpg',
    thumbnail: 'img/Thumbnails/01.jpg',
    title: 'Day in a Field',
    caption: 'Please, Don-Bot… look into your hard drive, and open your mercy file!',
    resolution: '1920x1200',
    isMatched: false,
  },
  {
    type: 'img',
    src: 'img/02.jpg',
    thumbnail: 'img/Thumbnails/02.jpg',
    title: 'Lake & Mountains',
    caption: 'Oh dear! She\'s stuck in an infinite loop, and he\'s an idiot! Well, that\'s love for you.',
    resolution: '1920x1200',
    isMatched: false,
  },
  {
    type: 'img',
    src: 'img/03.jpg',
    thumbnail: 'img/Thumbnails/03.jpg',
    title: 'Green Stuff',
    caption: "There's only one man I've ever called a coward, and that's Brian Doyle Murray. No, what I'm calling you is a television actor.",
    resolution: '1920x1200',
    isMatched: false,
  },
  {
    type: 'img',
    src: 'img/04.jpg',
    thumbnail: 'img/Thumbnails/04.jpg',
    title: 'Glaciers',
    caption: 'I can explain. It\'s very valuable. Alright, let\'s mafia things up a bit.',
    resolution: '1920x1200',
    isMatched: false,
  },
  {
    type: 'img',
    src: 'img/05.jpg',
    thumbnail: 'img/Thumbnails/05.jpg',
    title: 'Canyon Mountains',
    caption: "Ah, the 'Breakfast Club' soundtrack! I can't wait til I'm old enough to feel ways about stuff!",
    resolution: '1920x1200',
    isMatched: false,
  },
  {
    type: 'img',
    src: 'img/06.jpg',
    thumbnail: 'img/Thumbnails/06.jpg',
    title: 'Interesting shrubs',
    caption: "If rubbin' frozen dirt in your crotch is wrong, hey I don't wanna be right. There's no part of that sentence I didn't like!",
    resolution: '1920x1200',
    isMatched: false,
  },
  {
    type: 'img',
    src: 'img/07.jpg',
    thumbnail: 'img/Thumbnails/07.jpg',
    title: 'The Swamp',
    caption: "Now what? Ah, yes! John Quincy Adding Machine. He struck a chord with the voters when he pledged not to go on a killing spree.",
    resolution: '1920x1200',
    isMatched: false,
  },
  {
    type: 'img',
    src: 'img/08.jpg',
    thumbnail: 'img/Thumbnails/08.jpg',
    title: 'The Beach',
    caption: "That's right, baby. I ain't your loverboy Flexo, the guy you love so much. You even love anyone pretending to be him!",
    resolution: '1920x1200',
    isMatched: false,
  },
  {
    type: 'img',
    src: 'img/09.jpg',
    thumbnail: 'img/Thumbnails/09.jpg',
    title: 'Peaceful Pathway',
    caption: "Pansy. Morbo can't understand his teleprompter because he forgot how you say that letter that's shaped like a man wearing a hat.",
    resolution: '1920x1200',
    isMatched: false,
  },
  {
    type: 'img',
    src: 'img/10.jpg',
    thumbnail: 'img/Thumbnails/10.jpg',
    title: 'Mountain Waves',
    caption: "THE BIG BRAIN AM WINNING AGAIN! I AM THE GREETEST! NOW I AM LEAVING EARTH, FOR NO RAISEN!",
    resolution: '1920x1200',
    isMatched: false,
  },
  {
    type: 'img',
    src: 'img/11.jpg',
    thumbnail: 'img/Thumbnails/11.jpg',
    title: 'Eye from the Sky',
    caption: "Oh, how awful. Did he at least die painlessly? …To shreds, you say. Well, how is his wife holding up? …To shreds, you say.",
    resolution: '1920x1200',
    isMatched: false,
  },
  {
    type: 'img',
    src: 'img/12.jpg',
    thumbnail: 'img/Thumbnails/12.jpg',
    title: 'Field of Stuffs',
    caption: "Dear God, they'll be killed on our doorstep! And there's no trash pickup until January 3rd.",
    resolution: '1920x1200',
    isMatched: false,
  },
  {
    type: 'yt',
    title: 'Kap Slap - Harbor ft. Jake Etheridge',
    videoID: 'exgJUscSy3s',
    isMatched: false,
  },
  {
    type: 'yt',
    title: 'Vanic - Samurai (ft. Katy Tiz)',
    videoID: 'drcCOc2v80o',
    isMatched: false,
  },
  {
    type: 'yt',
    title: 'Flybear - Soon...',
    videoID: 'GXNGjs5WMGk',
    isMatched: false,
  },
  {
    type: 'yt',
    title: 'President Taft\'s Secret Pony Brigade',
    videoID: 'QrpCN014mS8',
    isMatched: false,
  },
  {
    type: 'yt',
    title: 'Creedence Clearwater Revival - "Travelin Band"',
    videoID: '4JoeGMazX4o',
    isMatched: false,
  },
  {
    type: 'yt',
    title: 'Otis Redding - Sitting On The Dock Of The Bay',
    videoID: 'wyPKRcBTsFQ',
    isMatched: false,
  },
  {
    type: 'yt',
    title: 'Bill Withers - Ain\'t No Sunshine',
    videoID: 'tIdIqbv7SPo',
    isMatched: false,
  }
];
